language: node_js
node_js:
  - "stable"
env:
  global: CC_TEST_REPORTER_ID=3bc558b89075b89d847800711bc3c52e47e3662ec719969db723cadc924dab16
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage
notifications:
  email: false

  